services:
  - type: web
    name: rental-project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn rental_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rental_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: rental-project-db
          property: connectionString

databases:
  - name: rental-project-db
    plan: free
