# Generated by Django 3.2 on 2025-07-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone1', models.CharField(max_length=20, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон 2')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('in_rent', 'В аренде'), ('completed', 'Завершена')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('paid', 'Оплачена'), ('unpaid', 'Не оплачена')], default='unpaid', max_length=20, verbose_name='Оплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rental_start', models.DateField(verbose_name='Начало аренды')),
                ('rental_end', models.DateField(verbose_name='Конец аренды')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('created_by_admin', models.BooleanField(default=False, verbose_name='Создана администратором')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название стойки')),
            ],
            options={
                'verbose_name': 'Стойка',
                'verbose_name_plural': 'Стойки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.tag', verbose_name='Родительский тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер полки')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.storage', verbose_name='Стойка')),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Доступное количество')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.shelf', verbose_name='Место хранения')),
                ('tags', models.ManyToManyField(blank=True, to='rental.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.order', verbose_name='Заявка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
            },
        ),
    ]
