# Generated by Django 3.2 on 2025-07-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['parent', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
