# Generated by Django 5.1.7 on 2025-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
