# Generated by Django 5.1.7 on 2025-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_product_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
