# Generated by Django 5.1.7 on 2025-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_tag_options_tag_order_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма залога'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название продакшена'),
        ),
        migrations.AddField(
            model_name='order',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название проекта'),
        ),
    ]
