# Generated by Django 5.1.7 on 2025-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма до скидки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачена'), ('paid', 'Оплачена')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='Основной телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дополнительный телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_end',
            field=models.DateField(verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_start',
            field=models.DateField(verbose_name='Дата начала аренды'),
        ),
    ]
